[project]
name = "local-rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Samir Vaniya", email = "skvaniya6275@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "ollama>=0.6.2",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
local-rag-project = "local_rag_project:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
